name: tcpip2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
  firebase_core: ^2.20.0
  firebase_database: ^10.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  csv: ^5.1.1
  intl: ^0.18.1
  percent_indicator: ^4.2.2
  geolocator: ^10.1.0
  permission_handler: ^11.4.0



  # iOS-style icons (default)
  cupertino_icons: ^1.0.8

  # ✅ Added for handling JSON and HTTP (optional for now)
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5


  # ✅ Optional, only needed if you plan to auto-generate model classes from JSON
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/backgroun.png
    - assets/logotap.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logotap.png"

flutter_native_splash:
color: "#ffffff"
image: assets/icon.png
fullscreen: true

android: true
ios: true

android_gravity: center
ios_content_mode: scaleAspectFit                     # fills entire screen
