// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKYPyCBWqJLsguMMEYLo-QEdy8_QFccEk',
    appId: '1:1009160932943:web:44ac6b5770b3b50071a43a',
    messagingSenderId: '1009160932943',
    projectId: 'mdp1-5f933',
    authDomain: 'mdp1-5f933.firebaseapp.com',
    databaseURL: 'https://mdp1-5f933-default-rtdb.firebaseio.com',
    storageBucket: 'mdp1-5f933.firebasestorage.app',
    measurementId: 'G-DHG8WM0G4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAObOX-JWSoUY09vV-KT8rHT5oAXSH4SUg',
    appId: '1:1009160932943:android:d00f501ea8907f1d71a43a',
    messagingSenderId: '1009160932943',
    projectId: 'mdp1-5f933',
    databaseURL: 'https://mdp1-5f933-default-rtdb.firebaseio.com',
    storageBucket: 'mdp1-5f933.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTKEX1i4R8khFGD2OdXSsmESPTbcBQayg',
    appId: '1:1009160932943:ios:130496fc7209528571a43a',
    messagingSenderId: '1009160932943',
    projectId: 'mdp1-5f933',
    databaseURL: 'https://mdp1-5f933-default-rtdb.firebaseio.com',
    storageBucket: 'mdp1-5f933.firebasestorage.app',
    iosBundleId: 'com.example.tcpip2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTKEX1i4R8khFGD2OdXSsmESPTbcBQayg',
    appId: '1:1009160932943:ios:130496fc7209528571a43a',
    messagingSenderId: '1009160932943',
    projectId: 'mdp1-5f933',
    databaseURL: 'https://mdp1-5f933-default-rtdb.firebaseio.com',
    storageBucket: 'mdp1-5f933.firebasestorage.app',
    iosBundleId: 'com.example.tcpip2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKYPyCBWqJLsguMMEYLo-QEdy8_QFccEk',
    appId: '1:1009160932943:web:b128a8c9ac9fe3d671a43a',
    messagingSenderId: '1009160932943',
    projectId: 'mdp1-5f933',
    authDomain: 'mdp1-5f933.firebaseapp.com',
    databaseURL: 'https://mdp1-5f933-default-rtdb.firebaseio.com',
    storageBucket: 'mdp1-5f933.firebasestorage.app',
    measurementId: 'G-K7QS89YN9Z',
  );
}
